[build]
functions = "funcs"
    publish = "build/"

[[redirects]]   
    from = “/”
    to = “https://iqdauntest.herokuapp.com”
    status = 200

[[headers]]
    for = “/"
    [headers.values]
    Access-Control-Allow-Origin = "”
